name: Trigger auto deployment for containerantps10

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ newbranch ]
    paths:
    - '**'
    - '.github/workflows/containerantps10-AutoDeployTrigger-556229eb-7b23-4154-807c-04a8f7dfb314.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: antuxtest.azurecr.io
          username: ${{ secrets.CONTAINERANTPS10_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERANTPS10_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: antuxtest.azurecr.io/containerantps10:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERANTPS10_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n containerantps10 -g MigrationDemo --server antuxtest.azurecr.io --username  ${{ secrets.CONTAINERANTPS10_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERANTPS10_REGISTRY_PASSWORD }}
            az containerapp update -n containerantps10 -g MigrationDemo --image antuxtest.azurecr.io/containerantps10:${{ github.sha }}
